language: android
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-25'
    
script:
  - cd app
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck --debug --stacktrace
  - sudo ls /usr/local/android-sdk/licenses
