language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - 'android-sdk-license-25'
    
# emulator for testing
before_script:
  - android list targets
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  # create license acception
  - sudo mkdir /usr/local/android-sdk/licenses
  - echo -e '\n8933bad161af4178b1185d1a37fbf41ea5269c55' | sudo tee /usr/local/android-sdk/licenses/android-sdk-license
  # start build
  - cd app
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck
