language: android
sudo: required
jdk: oraclejdk8

android:
  components:
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support

script:
  - cd app
  - chmod +x ./gradlew
  - ./gradlew build connectedCheck
